name: .NET Core

on:
  push:
    tags: [ build-* ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Cache nuget dependencies
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nugetcache-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: ${{ runner.os }}-nugetcache-

    - name: Build Reason
      run: "echo ref: ${{github.ref}} event: ${{github.event_name}}"

    - name: Build Solution
      run: |
        dotnet build GridMvc --configuration Release
        dotnet build GridBlazor --configuration Release
        dotnet build GridShared --configuration Release

    - name: Package Nuget
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        dotnet pack GridMvc --configuration Release --include-symbols --include-source --no-restore
        dotnet pack GridBlazor --configuration Release --include-symbols --include-source --no-restore
        dotnet pack GridShared --configuration Release --include-symbols --include-source --no-restore

    - name: Publish CI Packages
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        for package in $(find -name "*.nupkg"); do
          echo "${0##*/}": Pushing $package...
          dotnet nuget push $package --source https://nuget.pkg.github.com/timbze/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
        done
